name: build

on: [push, pull_request]

jobs:
  MRI:
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos', 'windows']
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4', head]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Install
        run: |
          gem build numo-narray.gemspec
          gem install numo-narray-*.gem
          bundle install
      - name: Tests
        run: rake test

  ruby-head-debug:
    name: Build on ruby-head-debug
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'debug' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Install
        run: |
          gem build numo-narray.gemspec
          gem install numo-narray-*.gem
          bundle install
      - name: Tests
        run: rake test

  Fedora:
    name: fedora
    runs-on: ubuntu-latest
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:rawhide
      - name: Get source
        uses: actions/checkout@v4
        with:
          path: 'numo-narray'
      - name: Create container and run tests
        run: |
          {
              echo 'FROM fedora:rawhide'
              echo 'RUN dnf -y update'
              echo 'RUN dnf -y install gcc-c++ git ruby-devel'
              echo 'RUN dnf clean all'
              echo 'COPY numo-narray numo-narray'
              echo 'WORKDIR /numo-narray'
              echo 'RUN gem install --no-document bundler'
              echo 'RUN gem build numo-narray.gemspec'
              echo 'RUN gem install numo-narray-*.gem'
              echo 'RUN bundle install'
              echo 'RUN bundle exec rake compile'
              echo 'RUN bundle exec rake test'
          } > podmanfile
          podman build --tag fedora_test -f ./podmanfile
